"use client";
import Link from "next/link";
import {useResource} from "@/lib/use-resource";
import type {ClassData} from "@/lib/types";
import {PageHeading,Notice,Loading,card,secondary} from "@/components/ui";
type Overview={name:string;class:ClassData;counts:{materials:number;assignments:number;pending_assignments:number;exams:number;completed_exams:number}};
export default function StudentHome(){
 const resource=useResource<Overview>("/student/overview");const data=resource.data;
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title={data?`Halo, ${data.name}`:"Beranda Siswa"} description="Materi, tugas, jadwal, dan ujian untuk kelas Anda ada di sini."/><Notice error={resource.error}/>{resource.loading?<Loading/>:<><div className="rounded-3xl bg-indigo-600 p-8 text-white"><p className="text-xs font-bold uppercase tracking-widest text-indigo-200">Kelas Anda</p><h2 className="mt-3 text-3xl font-black">{data?.class.ClassName||"Belum ditempatkan di kelas"}</h2><p className="mt-3 text-sm text-indigo-100">{data?.class.HomeroomTeacher?.Name?`Wali kelas: ${data.class.HomeroomTeacher.Name}`:"Hubungi administrator jika penempatan kelas belum tersedia."}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Materi belajar",data?.counts.materials||0],["Tugas belum dikumpulkan",data?.counts.pending_assignments||0],["Jadwal ujian",data?.counts.exams||0],["Ujian selesai",data?.counts.completed_exams||0]].map(([label,value])=><div key={label} className={card}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>)}</div><div className="grid gap-4 sm:grid-cols-2">{[["Materi Belajar","Baca modul dan referensi guru.","materials"],["Tugas Saya","Kumpulkan jawaban sebelum tenggat.","assignments"],["Ujian CBT","Kerjakan asesmen sesuai jadwal.","exams"],["Rekap Nilai","Lihat nilai tugas dan hasil ujian.","grades"]].map(([title,description,path])=><Link key={path} className={`${card} transition hover:border-indigo-300`} href={`/dashboard/student/${path}`}><h2 className="text-lg font-black">{title}</h2><p className="mt-2 text-sm text-slate-500">{description}</p></Link>)}</div><Link className={secondary} href="/dashboard/student/class">Lihat jadwal kelas</Link></>}</div>;
}
