"use client";
import Link from "next/link";
import {downloadFile} from "@/lib/api";
import {useResource,useAction} from "@/lib/use-resource";
import type {MaterialData,AssignmentData,ExamData,SessionData,SubjectData} from "@/lib/types";
import {PageHeading,Notice,card,button,secondary} from "@/components/ui";
export default function TeacherHome(){
 const session=useResource<SessionData>("/auth/me");const materials=useResource<{data:MaterialData[]}>("/teacher/materials");const tasks=useResource<{data:AssignmentData[]}>("/teacher/assignments");const exams=useResource<{data:ExamData[]}>("/teacher/exams");const subjects=useResource<{data:SubjectData[]}>("/teacher/subjects");const action=useAction();
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title={session.data?`Halo, ${session.data.name}`:"Beranda Guru"} description="Pantau pembelajaran, pengumpulan tugas, dan ujian kelas Anda."/><Notice error={session.error||materials.error||tasks.error||exams.error||subjects.error||action.error}/><div className="rounded-3xl bg-indigo-600 p-8 text-white"><h2 className="text-2xl font-black">Siapkan pembelajaran hari ini</h2><p className="my-3 text-indigo-100">Materi, tugas, dan ujian dipisahkan menurut kelas dan mata pelajaran yang Anda ampu.</p><Link href="/dashboard/teacher/classes" className="mt-3 inline-block rounded-xl bg-white px-5 py-3 text-sm font-bold text-indigo-700">Lihat jadwal mengajar</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Mapel",subjects.data?.data.length||0],["Materi",materials.data?.data.length||0],["Tugas",tasks.data?.data.length||0],["Ujian",exams.data?.data.length||0]].map(([label,value])=><div key={label} className={card}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>)}</div><div className="grid gap-5 md:grid-cols-2"><div className={`${card} space-y-4`}><h2 className="text-lg font-black">Akses cepat</h2>{[["Materi Belajar","materials"],["Tugas & Penilaian","assignments"],["Ujian CBT","exams"]].map(([label,path])=><Link key={path} href={`/dashboard/teacher/${path}`} className={`${secondary} flex justify-between`}>{label}<span aria-hidden="true">→</span></Link>)}</div><div className={`${card} space-y-4`}><h2 className="text-lg font-black">Laporan nilai</h2><p className="text-sm leading-relaxed text-slate-500">Unduh nilai tugas, status penilaian, dan hasil ujian siswa dari mapel yang Anda ampu.</p><button disabled={action.busy} className={button} onClick={()=>void action.run(()=>downloadFile("/teacher/export/report","Laporan_Nilai_Siswa.xlsx"))}>{action.busy?"Menyiapkan...":"Unduh Excel"}</button></div></div></div>;
}
