import {test,expect,type Page} from "@playwright/test";
const password="E2e-password-123";
test.beforeEach(async({page})=>{
 await page.route("**/api/**",route=>{
  const url=new URL(route.request().url());
  return route.continue({url:"http://localhost:18080"+url.pathname+url.search});
 });
});
async function login(page:Page,role:"admin"|"guru"|"siswa"){
 await page.goto("/login");
 await page.getByLabel("Identitas akun").fill(role+"@e2e.invalid");
 await page.getByLabel("Kata sandi",{exact:true}).fill(password);
 await page.getByRole("button",{name:"Masuk",exact:true}).click();
 await expect(page).toHaveURL(role==="admin"?/\/dashboard$/:new RegExp("/dashboard/"+(role==="guru"?"teacher":"student")+"$"));
 await expect(page.getByText("Portal "+(role==="admin"?"Admin":role==="guru"?"Guru":"Siswa"),{exact:true})).toBeVisible();
}
async function logout(page:Page){await page.getByRole("button",{name:"Keluar",exact:true}).click();await expect(page).toHaveURL(/\/login$/);}
test("student submission, teacher zero grade, student lock and report",async({page})=>{
 await login(page,"siswa");
 await page.goto("/dashboard/student/materials");
 await expect(page.getByRole("heading",{name:"Modul HTML"})).toBeVisible();
 await page.goto("/dashboard/student/assignments");
 await page.getByRole("button",{name:"Kumpulkan jawaban",exact:true}).click();
 await page.getByLabel("URL jawaban (http/https)").fill("https://example.org/my-work");
 await page.getByRole("button",{name:"Simpan jawaban"}).click();
 await expect(page.getByText("Jawaban tugas tersimpan.")).toBeVisible();
 await logout(page);
 await login(page,"guru");
 await page.goto("/dashboard/teacher/assignments/1");
 await expect(page.getByRole("heading",{name:"Siswa Uji"})).toBeVisible();
 await page.getByLabel(/Nilai \(0/).fill("0");
 await page.getByLabel("Catatan guru").fill("Perlu perbaikan");
 await page.getByRole("button",{name:"Simpan nilai"}).click();
 await expect(page.getByText("Sudah dinilai",{exact:true})).toBeVisible();
 await page.screenshot({path:"test-results/teacher-grading.png",fullPage:true});
 await logout(page);
 await login(page,"siswa");
 await page.goto("/dashboard/student/assignments");
 await expect(page.getByText("Perlu perbaikan")).toBeVisible();
 await expect(page.getByRole("button",{name:"Edit jawaban"})).toHaveCount(0);
 await page.goto("/dashboard/student/grades");
 await expect(page.getByRole("heading",{name:"Proyek Web"})).toBeVisible();
});
test("CBT answers survive refresh, automatic scoring and teacher results",async({page})=>{
 await login(page,"siswa");
 await page.goto("/dashboard/student/exams/1/take");
 await expect(page.getByRole("timer")).toBeVisible();
 await page.locator('input[value="B"]').check();
 await expect(page.getByRole("status").filter({hasText:"Semua jawaban tersimpan"})).toBeVisible();
 const before=await page.getByRole("timer").innerText();
 await page.reload();
 await expect(page.locator('input[value="B"]')).toBeChecked();
 const after=await page.getByRole("timer").innerText();
 expect(after<=before).toBeTruthy();
 await page.getByRole("button",{name:"Berikutnya"}).click();
 await page.locator('input[value="C"]').check();
 await page.getByRole("button",{name:"Kumpulkan Ujian",exact:true}).click();
 await page.getByRole("button",{name:"Ya, kumpulkan"}).click();
 await expect(page.getByRole("heading",{name:"Ujian selesai"})).toBeVisible();
 await expect(page.getByText("100.00",{exact:false})).toBeVisible();
 await page.reload();
 await expect(page.getByRole("heading",{name:"Ujian selesai"})).toBeVisible();
 await logout(page);
 await login(page,"guru");
 await page.goto("/dashboard/teacher/exams/1/results");
 await expect(page.getByText("Siswa Uji",{exact:true})).toBeVisible();
 await page.goto("/dashboard/teacher");
 const download=page.waitForEvent("download");
 await page.getByRole("button",{name:/Excel/}).click();
 expect((await download).suggestedFilename()).toMatch(/\.xlsx$/);
});
test("exam auto submits when countdown ends",async({page})=>{
 await login(page,"siswa");
 await page.goto("/dashboard/student/exams/2/take");
 await expect(page.getByRole("timer")).toBeVisible();
 await page.locator('input[value="A"]').check();
 await expect(page.getByRole("status").filter({hasText:"Semua jawaban tersimpan"})).toBeVisible();
 await expect(page.getByRole("heading",{name:"Ujian selesai"})).toBeVisible({timeout:75000});
 await expect(page.getByText("100.00",{exact:false})).toBeVisible();
});
test("admin class management, import template and saved settings",async({page})=>{
 await login(page,"admin");
 await page.goto("/dashboard/academic/classes");
 await page.getByRole("button",{name:/Tambah kelas/i}).click();
 await page.getByLabel("Nama kelas").fill("XI DKV BROWSER");
 await page.getByLabel("Jurusan",{exact:true}).selectOption("DKV");
 await page.getByRole("button",{name:/Simpan/}).click();
 await expect(page.getByText("XI DKV BROWSER",{exact:true})).toBeVisible();
 await page.goto("/dashboard/academic/import");
 const download=page.waitForEvent("download");
 await page.getByRole("button",{name:/template/i}).click();
 expect((await download).suggestedFilename()).toMatch(/\.xlsx$/);
 await page.goto("/dashboard/settings");
 await page.getByLabel("Nama sekolah").fill("SMK Browser Uji");
 await page.getByRole("button",{name:/Simpan/}).click();
 await expect(page.getByText("Pengaturan sekolah tersimpan.",{exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByLabel("Nama sekolah")).toHaveValue("SMK Browser Uji");
});
test("mobile menu, cross-role redirect and revoked logout token",async({page,request})=>{
 await page.setViewportSize({width:390,height:844});
 await login(page,"siswa");
 await page.getByRole("button",{name:"Buka navigasi"}).click();
 await page.getByRole("link",{name:"Kelas & Jadwal",exact:true}).click();
 await expect(page).toHaveURL(/\/student\/class$/);
 await expect(page.getByText("Pemrograman Web",{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:"test-results/student-mobile.png",fullPage:true});
 await page.goto("/dashboard/users/admin");
 await expect(page).toHaveURL(/\/dashboard\/student$/);
 const token=await page.evaluate(()=>localStorage.getItem("token"));
 const denied=await request.get("http://localhost:18080/api/admin/users",{headers:{Authorization:"Bearer "+token}});
 expect(denied.status()).toBe(403);
 await page.getByRole("button",{name:"Buka navigasi"}).click();
 await logout(page);
 const revoked=await request.get("http://localhost:18080/api/auth/me",{headers:{Authorization:"Bearer "+token}});
 expect(revoked.status()).toBe(401);
});

test("teacher creates material and exam; student takes published question",async({page})=>{
 await login(page,"guru");
 await page.goto("/dashboard/teacher/materials");
 await page.getByRole("button",{name:"Tambah materi",exact:true}).click();
 const materialForm=page.getByRole("dialog");
 await materialForm.getByLabel("Judul",{exact:true}).fill("Materi Browser");
 await materialForm.getByLabel("Mata pelajaran",{exact:true}).selectOption("1");
 await materialForm.getByLabel("Target kelas",{exact:true}).selectOption("1");
 await materialForm.getByLabel("URL materi (http/https)").fill("https://example.org/browser-module");
 await materialForm.getByRole("button",{name:"Simpan",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Materi Browser",exact:true})).toBeVisible();
 const material=page.getByRole("article").filter({has:page.getByRole("heading",{name:"Materi Browser",exact:true})});
 await material.getByRole("button",{name:"Edit",exact:true}).click();
 await page.getByRole("dialog").getByLabel("Judul",{exact:true}).fill("Materi Browser Revisi");
 await page.getByRole("dialog").getByRole("button",{name:"Simpan",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Materi Browser Revisi",exact:true})).toBeVisible();
 await page.goto("/dashboard/teacher/exams");
 await page.getByRole("button",{name:"Buat ujian",exact:true}).click();
 const examForm=page.getByRole("dialog");
 await examForm.getByLabel("Judul ujian").fill("Ujian Browser Baru");
 await examForm.getByLabel("Mapel",{exact:true}).selectOption("1");
 await examForm.getByLabel("Target kelas",{exact:true}).selectOption("1");
 await examForm.getByLabel("Tanggal (WIB)").fill(new Date(Date.now()-86400000).toISOString().slice(0,10));
 await examForm.getByRole("button",{name:"Buat ujian",exact:true}).click();
 const exam=page.getByRole("article").filter({has:page.getByRole("heading",{name:"Ujian Browser Baru",exact:true})});
 await expect(exam).toBeVisible();
 await exam.getByRole("link",{name:"Kelola soal",exact:false}).click();
 await expect(page).toHaveURL(/\/teacher\/exams\/\d+$/);
 const examId=page.url().split("/").pop();
 await page.getByLabel("Pertanyaan",{exact:true}).fill("Pertanyaan dibuat guru");
 for(const key of ["A","B","C","D"])await page.getByLabel("Pilihan "+key,{exact:true}).fill("Jawaban "+key);
 await page.getByLabel("Kunci jawaban",{exact:true}).selectOption("B");
 await page.getByRole("button",{name:"Tambah soal",exact:true}).click();
 await expect(page.getByRole("heading",{name:/Pertanyaan dibuat guru$/})).toBeVisible();
 await page.goto("/dashboard/teacher/exams");
 const published=page.getByRole("article").filter({has:page.getByRole("heading",{name:"Ujian Browser Baru",exact:true})});
 await published.getByRole("button",{name:"Buka ujian",exact:false}).click();
 await expect(published.getByText("Terbuka untuk siswa",{exact:true})).toBeVisible();
 await logout(page);
 await login(page,"siswa");
 await page.goto("/dashboard/student/materials");
 await expect(page.getByRole("heading",{name:"Materi Browser Revisi",exact:true})).toBeVisible();
 await page.goto("/dashboard/student/exams/"+examId+"/take");
 await expect(page.getByText("Pertanyaan dibuat guru",{exact:true})).toBeVisible();
 await page.locator('input[value="B"]').check();
 await page.getByRole("button",{name:"Kumpulkan Ujian",exact:true}).click();
 await page.getByRole("button",{name:"Ya, kumpulkan"}).click();
 await expect(page.getByRole("heading",{name:"Ujian selesai"})).toBeVisible();
 await expect(page.getByText("100.00",{exact:false})).toBeVisible();
});
