"use client";
import {useState,type FormEvent} from "react";
import {apiJSON,jsonBody} from "@/lib/api";
import {useResource,useAction} from "@/lib/use-resource";
import {DAYS,type ScheduleData,type SubjectData,type ClassData} from "@/lib/types";
import {PageHeading,Notice,Loading,Empty,Modal,Field,button,secondary,danger,inputClass,card} from "@/components/ui";
export default function Schedules({admin=false}:{admin?:boolean}){
 const resource=useResource<{data:ScheduleData[]}>("/schedules");const subjects=useResource<{data:SubjectData[]}>("/subjects");
 const classes=useResource<{data:ClassData[]}>(admin?"/admin/classes":null);const action=useAction();
 const [open,setOpen]=useState(false);const [editing,setEditing]=useState<ScheduleData|null>(null);const [day,setDay]=useState("");
 const rows=(resource.data?.data||[]).filter(row=>!day||row.DayOfWeek===day);
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);await action.run(async()=>{await apiJSON(editing?`/admin/schedules/${editing.ID}`:"/admin/schedules",{method:editing?"PUT":"POST",...jsonBody({class_id:Number(form.get("class_id")),subject_id:Number(form.get("subject_id")),day_of_week:form.get("day_of_week"),start_time:form.get("start_time"),end_time:form.get("end_time")})});setOpen(false);resource.reload();},"Jadwal tersimpan.");};
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title={admin?"Manajemen Jadwal":"Kelas & Jadwal"} description={admin?"Atur jadwal kelas. Server menolak waktu yang bentrok untuk kelas maupun guru.":"Jadwal mata pelajaran sesuai hak akses Anda."}>{admin&&<button className={button} onClick={()=>{setEditing(null);setOpen(true);}}>Tambah jadwal</button>}</PageHeading><Notice error={resource.error||action.error||subjects.error||classes.error} message={action.message}/><select aria-label="Filter hari" value={day} onChange={event=>setDay(event.target.value)} className={`${inputClass} sm:max-w-xs`}><option value="">Semua hari</option>{DAYS.map(value=><option key={value}>{value}</option>)}</select>
 {resource.loading?<Loading/>:!rows.length?<Empty text="Belum ada jadwal."/>:<div className="grid gap-5 md:grid-cols-2">{rows.map(row=><article key={row.ID} className={card}><p className="text-sm font-bold text-indigo-600">{row.DayOfWeek} · {row.StartTime}-{row.EndTime} WIB</p><h2 className="mt-3 text-xl font-black">{row.Subject.SubjectName}</h2><p className="my-3 text-sm text-slate-500">{row.Class.ClassName} · {row.Subject.Teacher?.Name || "Guru belum ditetapkan"}</p>{admin&&<div className="flex gap-2"><button className={secondary} onClick={()=>{setEditing(row);setOpen(true);}}>Edit</button><button className={danger} disabled={action.busy} onClick={()=>{if(window.confirm("Hapus jadwal ini?"))void action.run(async()=>{await apiJSON(`/admin/schedules/${row.ID}`,{method:"DELETE"});resource.reload();},"Jadwal dihapus.");}}>Hapus</button></div>}</article>)}</div>}
 {open&&<Modal title={editing?"Edit jadwal":"Tambah jadwal"} close={()=>setOpen(false)}><form onSubmit={save} className="space-y-5"><Notice error={action.error}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Kelas"><select name="class_id" required defaultValue={editing?.ClassID||""} className={inputClass}><option value="">Pilih kelas</option>{classes.data?.data?.map(row=><option key={row.ID} value={row.ID}>{row.ClassName}</option>)}</select></Field><Field label="Mata pelajaran"><select name="subject_id" required defaultValue={editing?.SubjectID||""} className={inputClass}><option value="">Pilih mapel</option>{subjects.data?.data.map(row=><option key={row.ID} value={row.ID}>{row.SubjectName}</option>)}</select></Field><Field label="Hari"><select name="day_of_week" defaultValue={editing?.DayOfWeek||"Senin"} className={inputClass}>{DAYS.map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Mulai (WIB)"><input name="start_time" required type="time" defaultValue={editing?.StartTime||""} className={inputClass}/></Field><Field label="Selesai (WIB)"><input name="end_time" required type="time" defaultValue={editing?.EndTime||""} className={inputClass}/></Field></div><button className={button} disabled={action.busy}>{action.busy?"Menyimpan...":"Simpan jadwal"}</button></form></Modal>}
 </div>;
}
