"use client";
import {useState,type FormEvent} from "react";
import Link from "next/link";
import {apiJSON,jsonBody} from "@/lib/api";
import {useResource,useAction} from "@/lib/use-resource";
import {dateLabel,type MaterialData,type AssignmentData,type ClassData,type SubjectData} from "@/lib/types";
import {PageHeading,Notice,Loading,Empty,Modal,ConfirmDelete,Field,button,secondary,danger,inputClass,card} from "@/components/ui";
type ContentRow=MaterialData|AssignmentData;
export default function TeacherContent({kind}:{kind:"materials"|"assignments"}){
 const materials=kind==="materials";
 const resource=useResource<{data:ContentRow[]}>(`/teacher/${kind}`);
 const subjects=useResource<{data:SubjectData[]}>("/teacher/subjects");const classes=useResource<{data:ClassData[]}>("/teacher/classes");const action=useAction();
 const [open,setOpen]=useState(false);const [editing,setEditing]=useState<ContentRow|null>(null);const [deleting,setDeleting]=useState<ContentRow|null>(null);const [search,setSearch]=useState("");
 const rows=(resource.data?.data||[]).filter(row=>[row.Title,row.ClassName,row.SubjectName].some(value=>value.toLowerCase().includes(search.toLowerCase())));
 const save=async(event:FormEvent<HTMLFormElement>)=>{
  event.preventDefault();const form=new FormData(event.currentTarget);
  const payload={title:form.get("title"),subject_id:Number(form.get("subject_id")),class_id:Number(form.get("class_id")),...(materials?{content_url:form.get("content_url")}:{deadline:form.get("deadline"),max_score:Number(form.get("max_score"))})};
  await action.run(async()=>{await apiJSON(editing?`/teacher/${kind}/${editing.ID}`:`/teacher/${kind}`,{method:editing?"PUT":"POST",...jsonBody(payload)});setOpen(false);resource.reload();},materials?"Materi tersimpan.":"Tugas tersimpan.");
 };
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title={materials?"Materi Belajar":"Tugas & Penilaian"} description={materials?"Bagikan modul, video, dan referensi sesuai kelas dan mapel yang Anda ampu.":"Tetapkan tenggat dan nilai maksimal, lalu nilai setiap pengumpulan siswa."}><button className={button} onClick={()=>{setEditing(null);setOpen(true);}}>Tambah {materials?"materi":"tugas"}</button></PageHeading><Notice error={resource.error||subjects.error||classes.error||action.error} message={action.message}/><input aria-label="Cari konten" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Cari judul, kelas, atau mapel..." className={inputClass}/>
 {resource.loading?<Loading/>:!rows.length?<Empty text={materials?"Belum ada materi.":"Belum ada tugas."}/>:<div className="grid gap-5 md:grid-cols-2">{rows.map(row=><article key={row.ID} className={card}><p className="text-xs font-bold text-indigo-600">{row.SubjectName} · {row.ClassName}</p><h2 className="mt-3 text-xl font-black">{row.Title}</h2>{"Deadline" in row&&<p className="my-3 text-sm text-slate-500">Tenggat: {dateLabel(row.Deadline,true)} · Maksimal {row.MaxScore} · {row.SubmissionCount} pengumpulan</p>}<div className="mt-5 flex flex-wrap gap-2">{"ContentURL" in row?<a className={secondary} href={row.ContentURL} target="_blank" rel="noopener noreferrer">Buka materi</a>:<Link className={button} href={`/dashboard/teacher/assignments/${row.ID}`}>Meja penilaian</Link>}<button className={secondary} onClick={()=>{setEditing(row);setOpen(true);}}>Edit</button><button className={danger} onClick={()=>setDeleting(row)}>Hapus</button></div></article>)}</div>}
 {open&&<Modal title={`${editing?"Edit":"Tambah"} ${materials?"materi":"tugas"}`} close={()=>setOpen(false)}><form onSubmit={save} className="space-y-5"><Notice error={action.error}/><Field label="Judul"><input name="title" required maxLength={255} defaultValue={editing?.Title||""} className={inputClass}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Mata pelajaran"><select name="subject_id" required defaultValue={editing?.SubjectID||""} className={inputClass}><option value="">Pilih mapel</option>{subjects.data?.data.map(row=><option key={row.ID} value={row.ID}>{row.SubjectName}</option>)}</select></Field><Field label="Target kelas"><select name="class_id" required defaultValue={editing?.ClassID||""} className={inputClass}><option value="">Pilih kelas</option>{classes.data?.data.map(row=><option key={row.ID} value={row.ID}>{row.ClassName}</option>)}</select></Field></div>
 {materials?<Field label="URL materi (http/https)"><input name="content_url" type="url" required defaultValue={editing&&"ContentURL" in editing?editing.ContentURL:""} className={inputClass}/></Field>:<div className="grid gap-4 sm:grid-cols-2"><Field label="Tanggal tenggat (akhir hari WIB)"><input name="deadline" type="date" required defaultValue={editing&&"Deadline" in editing?editing.Deadline.slice(0,10):""} className={inputClass}/></Field><Field label="Nilai maksimal"><input name="max_score" type="number" required min={1} max={1000} defaultValue={editing&&"MaxScore" in editing?editing.MaxScore:100} className={inputClass}/></Field></div>}
 {!subjects.data?.data.length&&<Notice error="Belum ada mapel yang Anda ampu. Minta administrator menetapkan pengampu terlebih dahulu."/>}<button disabled={action.busy||!subjects.data?.data.length} className={button}>{action.busy?"Menyimpan...":"Simpan"}</button></form></Modal>}
 {deleting&&<ConfirmDelete title={`Hapus ${deleting.Title}?`} description={materials?"Materi ini akan dihapus dari kelas siswa.":"Tugas dan semua jawaban/nilai terkait akan dihapus."} busy={action.busy} close={()=>setDeleting(null)} confirm={()=>void action.run(async()=>{await apiJSON(`/teacher/${kind}/${deleting.ID}`,{method:"DELETE"});setDeleting(null);resource.reload();},"Konten dihapus.")}/>}
 </div>;
}
