"use client";
import {useState,type FormEvent} from "react";
import {apiJSON,jsonBody} from "@/lib/api";
import {useResource,useAction} from "@/lib/use-resource";
import {dateLabel,type StudentTask} from "@/lib/types";
import {PageHeading,Notice,Loading,Empty,Modal,Field,button,secondary,inputClass,card} from "@/components/ui";
export default function StudentAssignments(){
 const resource=useResource<{data:StudentTask[]}>("/student/assignments");const action=useAction();const [selected,setSelected]=useState<StudentTask|null>(null);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);await action.run(async()=>{await apiJSON("/student/submissions",{method:"POST",...jsonBody({assignment_id:selected.assignment.ID,file_url:form.get("file_url")})});setSelected(null);resource.reload();},"Jawaban tugas tersimpan.");};
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title="Tugas Saya" description="Kumpulkan link jawaban yang dapat diakses guru. Jawaban dikunci setelah dinilai, termasuk nilai nol."><button className={secondary} onClick={resource.reload}>Muat ulang</button></PageHeading><Notice error={resource.error||action.error} message={action.message}/>
 {resource.loading?<Loading/>:!resource.data?.data.length?<Empty text="Belum ada tugas untuk kelas Anda."/>:<div className="grid gap-5 md:grid-cols-2">{resource.data.data.map(item=><article key={item.assignment.ID} className={card}><p className="text-xs font-bold text-indigo-600">{item.subject_name} · {item.is_graded?"Dinilai":item.has_submitted?"Sudah dikumpulkan":item.can_submit?"Belum dikumpulkan":"Tenggat berakhir"}</p><h2 className="mt-3 text-xl font-black">{item.assignment.Title}</h2><p className="my-3 text-sm text-slate-500">Tenggat: {dateLabel(item.assignment.Deadline,true)}</p>{item.is_graded?<div className="rounded-2xl bg-emerald-50 p-4 text-emerald-800"><p className="text-2xl font-black">{item.submission.Score}<span className="text-sm font-normal"> / {item.assignment.MaxScore}</span></p>{item.submission.Feedback&&<p className="mt-2 whitespace-pre-wrap text-sm">{item.submission.Feedback}</p>}</div>:<button className={button} disabled={!item.can_submit} onClick={()=>setSelected(item)}>{item.can_submit?item.has_submitted?"Edit jawaban":"Kumpulkan jawaban":"Pengumpulan ditutup"}</button>}{item.has_submitted&&<a className="mt-4 block text-sm font-bold text-indigo-600 underline" href={item.submission.FileURL} target="_blank" rel="noopener noreferrer">Lihat jawaban yang dikumpulkan</a>}</article>)}</div>}
 {selected&&<Modal title={selected.assignment.Title} close={()=>setSelected(null)}><form onSubmit={submit} className="space-y-5"><Notice error={action.error}/><Field label="URL jawaban (http/https)"><input name="file_url" type="url" required defaultValue={selected.has_submitted?selected.submission.FileURL:""} className={inputClass}/></Field><p className="text-sm text-slate-500">Pastikan izin berbagi link memungkinkan guru membaca jawaban Anda.</p><button disabled={action.busy} className={button}>{action.busy?"Mengirim...":"Simpan jawaban"}</button></form></Modal>}
 </div>;
}
