"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {BookOpen} from "lucide-react";
import {apiJSON,jsonBody,roleHome} from "@/lib/api";
import {useAction} from "@/lib/use-resource";
import {Field,Notice,inputClass,button} from "@/components/ui";
export default function LoginPage(){
 const router=useRouter();const action=useAction();const [visible,setVisible]=useState(false);
 const login=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);await action.run(async()=>{const data=await apiJSON<{token:string;role_id:number}>("/login",{method:"POST",...jsonBody({identifier:form.get("identifier"),password:form.get("password")})});localStorage.setItem("token",data.token);window.dispatchEvent(new Event("session-changed"));router.replace(roleHome(data.role_id));});};
 return <main className="flex min-h-screen bg-slate-50 text-slate-900"><section className="relative hidden w-1/2 items-center overflow-hidden bg-indigo-900 p-12 text-white lg:flex"><div className="absolute -right-24 top-10 h-96 w-96 rounded-full bg-indigo-600/60 blur-3xl"/><div className="relative max-w-lg"><BookOpen size={52}/><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-indigo-300">LMS Citra Negara</p><h1 className="mt-5 text-5xl font-black leading-tight">Belajar, berkarya,<br/>dan tumbuh bersama.</h1><p className="mt-6 text-lg leading-relaxed text-indigo-200">Satu portal untuk materi belajar, tugas, ujian CBT, dan pengelolaan akademik enam jurusan.</p><p className="mt-10 text-sm font-bold text-indigo-200">PPLG · TJKT · DKV · BDR · PERHOTELAN · MPLB</p></div></section><section className="flex w-full items-center justify-center p-6 lg:w-1/2"><div className="w-full max-w-md space-y-6"><Link href="/" className="text-sm font-bold text-indigo-600">← Kembali ke beranda</Link><div><h2 className="mt-8 text-3xl font-black">Masuk ke portal</h2><p className="mt-2 text-sm text-slate-500">Gunakan NIS, NISN, NIP, atau email akun Anda.</p></div><Notice error={action.error}/><form onSubmit={login} className="space-y-5"><Field label="Identitas akun"><input name="identifier" required autoComplete="username" autoFocus className={inputClass} placeholder="NIS / NISN / NIP / email"/></Field><Field label="Kata sandi"><input name="password" type={visible?"text":"password"} required autoComplete="current-password" className={inputClass}/></Field><label className="flex items-center gap-2 text-sm text-slate-500"><input type="checkbox" checked={visible} onChange={event=>setVisible(event.target.checked)}/>Tampilkan kata sandi</label><button disabled={action.busy} className={`${button} w-full`}>{action.busy?"Memproses...":"Masuk"}</button></form><p className="text-sm leading-relaxed text-slate-500">Belum punya akun atau lupa kata sandi? Hubungi administrator atau wali kelas sekolah Anda.</p><Link href="/help" className="inline-block text-sm font-bold text-indigo-600">Panduan penggunaan</Link></div></section></main>;
}
