"use client";
import {useState,type FormEvent} from "react";
import Link from "next/link";
import {apiJSON,jsonBody,downloadFile} from "@/lib/api";
import {useResource,useAction} from "@/lib/use-resource";
import {calendarLabel,type ExamData,type SubjectData,type ClassData} from "@/lib/types";
import {PageHeading,Notice,Loading,Empty,Modal,ConfirmDelete,Field,button,secondary,danger,inputClass,card} from "@/components/ui";
export default function TeacherExams(){
 const resource=useResource<{data:ExamData[]}>("/teacher/exams");const subjects=useResource<{data:SubjectData[]}>("/teacher/subjects");const classes=useResource<{data:ClassData[]}>("/teacher/classes");const action=useAction();
 const [open,setOpen]=useState(false);const [deleting,setDeleting]=useState<ExamData|null>(null);
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);await action.run(async()=>{await apiJSON("/teacher/exams",{method:"POST",...jsonBody({title:form.get("title"),subject_id:Number(form.get("subject_id")),class_id:Number(form.get("class_id")),type:form.get("type"),date:form.get("date"),duration:Number(form.get("duration"))})});setOpen(false);resource.reload();},"Jadwal ujian dibuat. Tambahkan soal sebelum membuka ujian.");};
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title="Ujian CBT" description="Buat jadwal, susun soal, buka ujian, dan pantau hasil siswa."><div className="flex flex-wrap gap-3"><button disabled={action.busy} className={secondary} onClick={()=>void action.run(()=>downloadFile("/teacher/export/report","Laporan_Nilai_Siswa.xlsx"))}>Export nilai</button><button className={button} onClick={()=>setOpen(true)}>Buat ujian</button></div></PageHeading><Notice error={resource.error||subjects.error||classes.error||action.error} message={action.message}/>
 {resource.loading?<Loading/>:!resource.data?.data.length?<Empty text="Belum ada ujian untuk mapel Anda."/>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{resource.data.data.map(exam=><article className={card} key={exam.ID}><p className="text-xs font-bold text-purple-600">{exam.Type} · {exam.SubjectName}</p><h2 className="mt-3 text-xl font-black">{exam.Title}</h2><p className="my-3 text-sm text-slate-500">{exam.ClassName} · {calendarLabel(exam.Date)}<br/>{exam.Duration} menit · {exam.QuestionCount} soal · {exam.CompletedCount} selesai</p><p className="mb-4 text-sm font-bold text-indigo-600">{exam.IsActive?"Terbuka untuk siswa":"Draf / ditutup"}</p><div className="flex flex-wrap gap-2"><Link className={secondary} href={`/dashboard/teacher/exams/${exam.ID}`}>Kelola soal</Link><Link className={secondary} href={`/dashboard/teacher/exams/${exam.ID}/results`}>Hasil siswa</Link><button className={button} disabled={action.busy} onClick={()=>void action.run(async()=>{await apiJSON(`/teacher/exams/${exam.ID}/active`,{method:"PUT",...jsonBody({is_active:!exam.IsActive})});resource.reload();},"Status ujian diperbarui.")}>{exam.IsActive?"Tutup ujian":"Buka ujian"}</button><button className={danger} disabled={exam.IsActive} onClick={()=>setDeleting(exam)}>Hapus</button></div></article>)}</div>}
 {open&&<Modal title="Buat jadwal ujian" close={()=>setOpen(false)}><form onSubmit={create} className="space-y-5"><Notice error={action.error}/><Field label="Judul ujian"><input name="title" required maxLength={255} className={inputClass}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Mapel"><select name="subject_id" required className={inputClass}><option value="">Pilih mapel</option>{subjects.data?.data.map(row=><option key={row.ID} value={row.ID}>{row.SubjectName}</option>)}</select></Field><Field label="Target kelas"><select name="class_id" required className={inputClass}><option value="">Pilih kelas</option>{classes.data?.data.map(row=><option key={row.ID} value={row.ID}>{row.ClassName}</option>)}</select></Field><Field label="Jenis ujian"><select name="type" className={inputClass}><option>UH</option><option>STS</option><option>SAS</option></select></Field><Field label="Tanggal (WIB)"><input name="date" type="date" required className={inputClass}/></Field><Field label="Durasi (menit)"><input name="duration" type="number" min={1} max={1440} required defaultValue={90} className={inputClass}/></Field></div><button disabled={action.busy||!subjects.data?.data.length} className={button}>{action.busy?"Menyimpan...":"Buat ujian"}</button></form></Modal>}
 {deleting&&<ConfirmDelete title={`Hapus ${deleting.Title}?`} description="Soal, jawaban, dan semua hasil ujian ini ikut dihapus." busy={action.busy} close={()=>setDeleting(null)} confirm={()=>void action.run(async()=>{await apiJSON(`/teacher/exams/${deleting.ID}`,{method:"DELETE"});setDeleting(null);resource.reload();},"Ujian dihapus.")}/>}
 </div>;
}
