"use client";
import Link from "next/link";
import {useResource} from "@/lib/use-resource";
import type {UserData,ClassData} from "@/lib/types";
import {PageHeading,Notice,Loading,card,secondary} from "@/components/ui";
export default function AdminHome(){
 const users=useResource<{data:UserData[]}>("/admin/users");const classes=useResource<{data:ClassData[]}>("/admin/classes");
 const rows=users.data?.data||[];
 return <div className="mx-auto max-w-7xl space-y-6"><PageHeading title="Beranda Administrator" description="Kelola akun dan struktur akademik seluruh jurusan."/><Notice error={users.error||classes.error}/>{users.loading?<Loading/>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Pengguna",rows.length],["Guru",rows.filter(user=>user.RoleID===2).length],["Siswa",rows.filter(user=>user.RoleID===3).length],["Kelas",classes.data?.data.length||0]].map(([label,value])=><div key={label} className={card}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>)}</div><div className={card}><h2 className="text-lg font-black">Penempatan siswa</h2><p className="my-3 text-sm text-slate-500">{rows.filter(user=>user.RoleID===3&&!user.ClassID).length} siswa belum memiliki kelas.</p><Link className={secondary} href="/dashboard/academic/classes">Kelola kelas dan wali kelas</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[["Data Siswa","users/siswa"],["Data Guru","users/guru"],["Mata Pelajaran","academic/subjects"],["Jadwal Kelas","academic/schedules"],["Import Excel","academic/import"],["Pengaturan Sekolah","settings"]].map(([label,path])=><Link key={path} href={`/dashboard/${path}`} className={`${card} font-bold transition hover:border-indigo-300`}>{label}<span className="ml-2 text-indigo-600">?</span></Link>)}</div><div className={card}><h2 className="mb-4 text-lg font-black">Akun terbaru</h2><div className="space-y-4">{rows.slice(0,5).map(user=><div key={user.ID} className="flex flex-wrap justify-between gap-2 border-b border-slate-100 pb-3"><span className="font-bold">{user.Name}</span><span className="text-sm text-slate-500">{user.Email}</span></div>)}</div></div></>}</div>;
}
